name: Build demo application

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib openocd
      - uses: actions/checkout@v3
      - run: cmake --preset ci/efm32gg
        working-directory: demo
      - run: cmake --build --preset ci/efm32gg/release
        working-directory: demo
