name: TraceCompass plugin

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build plugin with Maven
      run: mvn -B clean verify site --file tracecompass-plugin/pom.xml

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: tracecompas-orbcode-trace-plugin
        path: tracecompass-plugin/updatesite/target/repository/**/*.*
